# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'dmd' -Path (Join-Path (Join-Path $toolsDir 'bin') 'dmd.bat')
Install-BinFile -Name 'docker-stop' -Path (Join-Path (Join-Path $toolsDir 'bin') 'docker-stop.bat')
